---
# Tasks specific for RedHat systems

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    priority: "{{ item.priority | default('99') }}"
    state: "{{ item.state | default('present') }}" 
  with_items: "{{ zabbix_agent_repo_yum }}"
  register: yum_repo_installed
  become: true
  tags:
    - init
    - zabbix-agent    


- name: "RedHat | Installing zabbix-agent packages"
  package:
    pkg:
      - "{{ zabbix_agent_package }}"
      - "{{ zabbix_sender_package }}"
      - "{{ zabbix_get_package }}"
    state: "latest"
  register: zabbix_agent_package_installed
  until: zabbix_agent_package_installed is succeeded
  notify: restart zabbix-agent service
  become: true
  tags:
    - init
    - zabbix-agent    

