---
# handlers file for zabbix_agent
- name: restart win zabbix agent
  win_service:
    name: "{{ zabbix_win_agent_service }}"
    state: restarted
    enabled: yes
  when:
    - ansible_os_family == "Windows"

- name: restart zabbix-agent service
  service:
    name: zabbix-agent
    state: restarted
    enabled: true    

